In [17]:
from numpy import *
import numpy.linalg as linalg
import sympy as sp
from sympy import Matrix, solve_linear_system, Eq

In [18]:
# --------------------------Q1
A = mat('2 -4; 1 3')
B = mat('4 -1; 2 0')
C = mat('4; 3')
D = mat('3; 1')
E = mat('-3 2 0; 1 -1 -2')
print("A\n", A)
print("B\n", B)
print("C\n", C)
print("D\n", D)
print("E\n", E)

A
 [[ 2 -4]
 [ 1  3]]
B
 [[ 4 -1]
 [ 2  0]]
C
 [[4]
 [3]]
D
 [[3]
 [1]]
E
 [[-3  2  0]
 [ 1 -1 -2]]


In [ ]:
# --------------------------Q2 (use matrices in Q1)
print("i) A+B: \n", A+B, "\n")
print("ii) 3B: \n", 3*B, "\n")
print("iii) AC: \n", A*C, "\n")
print("iv) (AC)^T: \n", (A*C).T, "\n")
print("v) AE: \n", A*E, "\n")
print("vi) AD: \n", A*D, "\n")
print("vii) B + D: \n", B+D, "\n")
print("viii) B - 2A: \n", B - 2*A, "\n")

In [ ]:
# --------------------------Q3
mA = mat('1 -1 1; 0 -2 1; -2 -3 0')
mA = Matrix(mA)
print("Determinant of matrix mA = ", mA.det())

mB = Matrix(([1, 4, 7], [2, 5, 8], [3, 6, 9]))
mB = Matrix(mB)
print("Determinant of matrix mB = ", mB.det())

mC = mat('3 -3 1; -2 2 -1; -4 5 -2')
mC = Matrix(mC)
print("Determinant of matrix mC = ", mC.det())

mD = mat('1 2 3; 0 1 4; 5 6 0')
mD = Matrix(mD)
print("Determinant of matrix mD = ", mD.det())

mE = mat('24 18 5; 20 -15 -4; -5 4 1')
mE = Matrix(mE)
print("Determinant of matrix mE = ", mE.det())

mF = mat('-1 3 -3; 0 -6 5; -5 -3 1')
mF = Matrix(mF)
print("Determinant of matrix mF = ", mF.det())

mG = mat('2 1 1; 3 2 1; 2 1 2')
mG = Matrix(mG)
print("Determinant of matrix mG = ", mG.det())

mH = mat('9 8 7; 6 5 14; 3 2 1')
mH = Matrix(mH)
print("Determinant of matrix mH = ", mH.det())

In [ ]:
# --------------------------Q4 (use matrices in Q3)
mA_inv = mat(mA.inv())
print("Inverse of mA = \n", mA_inv, "\n")
# mB_inv = mat(mB.inv())       # singular matrix
# print(mB_inv)
print("No inverse matrix for mB as it is singular matrix(determinant of mB is 0)\n")
mC_inv = mat(mC.inv())
print("Inverse of mC = \n", mC_inv, "\n")
mD_inv = mat(mD.inv())
print("Inverse of mD = \n", mD_inv, "\n")
mE_inv = mat(mE.inv())
print("Inverse of mE = \n", mE_inv, "\n")
mF_inv = mat(mF.inv())
print("Inverse of mF = \n", mF_inv, "\n")
mG_inv = mat(mG.inv())
print("Inverse of mG = \n", mG_inv, "\n")
mH_inv = mat(mH.inv())
print("Inverse of mH = \n", mH_inv, "\n")

In [ ]:
# --------------------------Q5
# i)
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')

x, y = sp.symbols('x y')

eq1 = Eq(2*x+3*y, 11)
eq2 = Eq(-3*x-4*y, -13)
display(eq1)
display(eq2)

row1 = [2, 3, 11]
row2 = [-3, -4, -13]

system = Matrix((row1, row2))
display(system)

solve_linear_system(system, x, y)

In [ ]:
# --------------------------Q5
# ii)
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')
eq3 = sp.Function('eq3')

x, y, z = sp.symbols('x y z')

eq1 = Eq(x+y+z, 7)
eq2 = Eq(2*x-2*y+3*z, 14)
eq3 = Eq(-x-y+z, 1)
display(eq1)
display(eq2)
display(eq3)

row1 = [1, 1, 1, 7]
row2 = [2, -2, 3, 14]
row3 = [-1, -1, 1, 1]

system = Matrix((row1, row2, row3))
display(system)

solve_linear_system(system, x, y, z)

In [ ]:
# --------------------------Q5
# iii)
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')
eq3 = sp.Function('eq3')

x, y, z = sp.symbols('x y z')

eq1 = Eq(8*x-7*y+10*z, 15)
eq2 = Eq(2*x+3*y+8*z, 7)
eq3 = Eq(4*x-5*y+2*z, 9)
display(eq1)
display(eq2)
display(eq3)

row1 = [8, -7, 10, 15]
row2 = [2, 3, 8, 7]
row3 = [4, -5, 2, 9]

system = Matrix((row1, row2, row3))
display(system)

solve_linear_system(system, x, y, z)

In [ ]:
# --------------------------Q5
# iv)
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')
eq3 = sp.Function('eq3')

x, y, z = sp.symbols('x y z')

eq1 = Eq(x+y+z, 6)
eq2 = Eq(2*y+5*z, -4)
eq3 = Eq(2*x+5*y-z, 27)
display(eq1)
display(eq2)
display(eq3)

row1 = [1, 1, 1, 6]
row2 = [0, 2, 5, -1]
row3 = [2, 5, -1, 27]

system = Matrix((row1, row2, row3))
display(system)

solve_linear_system(system, x, y, z)

In [ ]:
# --------------------------Q5
# v)
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')
eq3 = sp.Function('eq3')

x, y, z= sp.symbols('x y z')

eq1 = Eq(2*x-y+6*z, 10)
eq2 = Eq(-3*x+4*y-5*z, 11)
eq3 = Eq(8*x-7*y-9*z, 12)
display(eq1)
display(eq2)
display(eq3)

row1 = [2, -1, 6, 10]
row2 = [-3, 4, -5, 11]
row3 = [8, -7, -9, 12]

system = Matrix((row1, row2, row3))
display(system)

solve_linear_system(system, x, y, z)

In [ ]:
# --------------------------Q5
# vi)
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')
eq3 = sp.Function('eq3')

x, y, z= sp.symbols('x y z')

eq1 = Eq(2*x-3*y, 4)
eq2 = Eq(-x+4*y-z, 11)
eq3 = Eq(6*x-5*y+2*z, -3)
display(eq1)
display(eq2)
display(eq3)

row1 = [2, -3, 0, 4]
row2 = [-1, 4, -1, 11]
row3 = [6, -5, 2, -3]

system = Matrix((row1, row2, row3))
display(system)

solve_linear_system(system, x, y, z)

In [ ]:
# --------------------------Q6
m1 = mat('0 1; -2 -3')
print("m1 = \n", m1)
eig_val1, eig_vec1 = linalg.eig(m1)
print("\neigen values: ")
for i in range(eig_val1.__len__()):
    print(eig_val1[i], end=" ")             # round(eig_val1[i]) if imprecision occur

print("\n")
m2 = mat('4 -2 1; 2 0 1; 2 -2 3')
print("m2 = \n", m2)
eig_val2, eig_vec2 = linalg.eig(m2)
print("\neigen values: ")
for i in range(eig_val2.__len__()):
    print(round(eig_val2[i]), end=" ")      # round(eig_val1[i]) if imprecision occur

print("\n")
m3 = mat('4 7 1; 0 -3 8; 0 0 2')
print("m3 = \n", m3)
eig_val3, eig_vec3 = linalg.eig(m3)
print("\neigen values: ")
for i in range(eig_val3.__len__()):
    print(eig_val3[i], end=" ")             # round(eig_val3[i]) if imprecision occur

In [ ]:
# --------------------------Q7
S = mat('4.0 2.0 0.6;'
        '4.2 2.1 0.59;'
        '3.9 2.0 0.58;'
        '4.3 2.1 0.62;'
        '4.1 2.2 0.63')

print("Matrix S =\n", S)
# calculate the mean of each column
colMean = mean(S.T, axis=1)
M = colMean.T
print("\nMean of each column:\n", M)
# center columns by subtracting colum means
deviationScoreMatrix = S - M
print("\nDeviation Score Matrix(Center columns):\n", deviationScoreMatrix)
# calculate covariance matrix of centered matrix
covS = cov(deviationScoreMatrix.T)
print("\nCovariance matrix:\n", covS)
# eigendecomposition of covariance matrix
eigVal, eigVec = linalg.eig(covS)
print("\nEigenvalues:\n", eigVal)
print("\nFeature vector U:\n", eigVec)
for i in range(eigVec.__len__()):
    print("\nVector",i+1, "when eigenvalue =", eigVal[i], ":\n", (eigVec[:, i]))

# project data
P = eigVec[:, 0].T.dot(deviationScoreMatrix.T)
print("\nProject data (1st Principal Component of the raw data):\n", P.T)

In [ ]:
row1 = [2, -1, -4]
row2 = [3, -1, -2]
system = Matrix((row1, row2))
display(system)

In [ ]:
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')

x, y = sp.symbols('x y')

eq1 = Eq(2*x+3*y, 11)
eq2 = Eq(-3*x-4*y, -13)
display(eq1)
display(eq2)

row1 = [2, 3, 11]
row2 = [-3, -4, -13]

system = Matrix((row1, row2))
display(system)

solve_linear_system(system, x, y)

In [ ]:
# Lab2Q7 code from lecturer
from numpy import mean, cov, double, cumsum, dot, linalg, array, ndim
from pylab import plot, subplot, axis, stem, show, figure

def princomp(A):
    M = (A - mean(A.T, axis=1)).T
    [latent, coeff] = linalg.eig(cov(M))
    score = dot(coeff.T, M)
    return coeff, score, latent

S = array([[4.0, 2.0, 0.6], [4.2, 2.1, 0.59], [3.9, 2.0, 0.58],
           [4.3, 2.1, 0.62], [4.1, 2.2, 0.63]])
coeff, score, latent = princomp(S.T)
figure()
subplot(121)
m = mean(S, axis=1)
plot([0, -coeff[0,0]*2]+m[0], [0, -coeff[0,1]*2]+m[1], '--k')
plot([0, coeff[1,0]*2]+m[0], [0, coeff[1,1]*2]+m[1], '--k')
plot(S[0,:], S[1,:], '*g')
axis('equal')
show()